### PR TITLE
Boston precincts council districts 10 21 2022

### PR DESCRIPTION
**Pull request by spencer-rdh**

### CODE REVIEW

**Review by rdhlily — APPROVED** [review]
Looks good!

**Comment by peter-redistricting-data-hub** [comment]
Pending this final check, looks good!

**Comment by peter-redistricting-data-hub** [comment]
This is good!

**Comment by peter-redistricting-data-hub** [comment]
This is good!

**Comment by peter-redistricting-data-hub** [comment]
Looks good!

**Pull request merged**
